version: 0.2
phases:
  install:
    nodejs: 18
  pre_build:
    commands:
      - echo installing npm dependencies
      - npm install --force
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive --acl public-read ./build s3://vithi-resume-frontend
      - aws cloudfront create-invalidation --distribution-id E2KMAF247NQFL1 --paths '/*'